name: Python Tests

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ENC_KEY: ${{ secrets.ENC_KEY }}
        IP_SALT: ${{ secrets.IP_SALT }}
        SESSION_SALT: ${{ secrets.SESSION_SALT }}

      run: |
        pytest  # Run pytest